import { strict as assert } from 'node:assert';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
const { restrictedRoute: route, restrictedBody: body, restrictedRoutes, restrictedBodies } = await import(pathToFileURL(process.argv[2]).href);
assert(route('GET','/api/sessions?all=true'));
assert(route('GET','/api/default/chats/5531999999999%40c.us/messages/true_abc?downloadMedia=false'));
for (const path of ['/api/default/media/convert/voice','/api/default/chats','/api/default/contacts','/api/sendImage','/api/sessions/default','/api/sessions/other/start','/api/sendText?x=1','/api/sendText/']) assert(!route('POST',path), path);
for (const path of ['/api/default/chats/5531999999999%40c.us/messages/id?downloadMedia=true','/api/default/chats/123%40g.us/messages/id?downloadMedia=false','/api/default/chats/5531999999999%40c.us/messages','/api/default/auth/qr?x=1']) assert(!route('GET',path),path);
const message={session:'default',chatId:'5531999999999@c.us',text:'Contato #123',linkPreview:false};
assert(body('/api/sendText',message));
for(const change of [{linkPreview:true},{session:'other'},{chatId:'123@g.us'},{text:''},{text:'x'.repeat(4001)},{file:{url:'http://127.0.0.1/'}},{reply_to:'id'}]) assert(!body('/api/sendText',{...message,...change}));
assert(body('/api/sessions',{name:'default',start:true}));
assert(!body('/api/sessions',{name:'default',start:true,config:{webhooks:[{url:'http://internal/'}]}}));
let called=false,status=0;
const res={status(code){status=code;return this;},json(){return this;}};
const fixtureKey='test-client-key-'.repeat(4);
process.env.WAHA_ASSISTANT_CLIENT_KEY_HASH='sha512:'+createHash('sha512').update(fixtureKey).digest('hex');
restrictedRoutes({method:'GET',originalUrl:'/api/sessions?all=true',headers:{origin:'http://evil.test','x-api-key':fixtureKey}},res,()=>called=true);
assert.equal(status,403);assert.equal(called,false);
restrictedBodies({method:'POST',originalUrl:'/api/sendText',body:{...message,linkPreview:true}},res,()=>called=true);
assert.equal(status,400);assert.equal(called,false);
console.log('Restricted WAHA policy: allowed flow, media/history/origin/config/preview blocks passed');
