const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'../extension');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
const bg=fs.readFileSync(path.join(root,'background.js'),'utf8');
const content=fs.readFileSync(path.join(root,'content.js'),'utf8');
const capture=fs.readFileSync(path.join(root,'capture.js'),'utf8');
assert.equal(manifest.version,'2.4.1');
assert.ok(manifest.optional_host_permissions.includes('https://*/*'));
assert.match(bg,/bridgeOutbox22/);
assert.match(bg,/injectGenericBridge/);
assert.match(bg,/tabs\.onUpdated\.addListener/);
assert.match(content,/packetCount/);
assert.match(content,/recoverLatestContract/);
assert.match(content,/forceContractScan/);
assert.ok(content.includes('Some SPA renderers expose a fenced/code response with escaped newlines'));
assert.match(capture,/multiTicket/);
assert.match(capture,/Vincule cada print ao chamado correto/);
console.log('Bridge 2.4.1: outbox, reinjeção genérica, manifesto seguro e isolamento de evidência multi-ticket presentes.');
